binop_separator = "Front"
blank_lines_lower_bound = 0
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
force_explicit_abi = true
hard_tabs = true
imports_layout = "Vertical"
indent_style = "Block"
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = true
struct_field_align_threshold = 10
struct_lit_single_line = false
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = false
use_try_shorthand = false
wrap_comments = true
fn_single_line = false
fn_args_layout = "Compressed"

max_width = 120
use_small_heuristics = "Off"